### ISSUE TITLE
Create option for toggle recording start/stop

### ISSUE THREAD

**Issue by realbearsmith** [maxkrieger/voiceliner#64]
I'm loving Voiceliner so far, but I'm finding the _hold to record_ input method a bit unwieldy for my use case.

I'd like to use Voiceliner on a daily basis as I do some of my best thinking out loud, but these instances often come up in meetings or during longer conversations where holding the record button the whole time isn't feasible. It'd be great to be able to just press to record and press to stop recording.

**Comment by maxkrieger** [comment]
Have you tried that? It works ;)

**Comment by realbearsmith** [comment]
> Have you tried that? It works ;)

Oh no, I'm dumb.

Related then, maybe there's a way to make that easier/noticeable. Like _Tap or hold to record_? Just a thought.

Thanks!

**Comment by lpstandardrp** [comment]
Oh man! Glad I looked this up!! 
YEP. Same boat as OP.  i find Unencumbered Undistracted FLOWing thoughts, Ideas, "spitballing" Perhaps the most inaoired and authentic and void of potential influence... *raw*~ ANY distractions are HUGE detractors away from "the zone" "flow" (non-religious, and/or religious "communion" (Quentin Tarantino ince said his pencil was his "antenna to God"... 

Point being... 
"Hold to record" (who finds this *most* useful? To first play devil's advocate and with I believe good reason, I could make a case and strong aegument for leaving "hold" as the primary instruction and/or button text. Why? In case someone taps and forgets to tap a second time to stop the recording (I could foresee this *potentially* causing problems, crashes, etc. ... unless 'you' are/thebuser is as fortunate and blessed as I have been  using "Audio Recorder" (F-Droid)(Desert Island app <333 ...333) in recording many 20-30 minute dialogues without a hitch. (To be fair I have, to my recollection, had no (haha... this is a high bar) crashes in which I lost work, though, I have a **strong** feeling I experienced a loss of sorts and if so I believe my storage (completely my fault, and a dang good lesson)  was near if not completely full.  

My point:
"Tap" might benefit users (it could have saved me time here and now kand thus potentially  you) had I seen "tap" in the app somewhere... (even if it were disclosed in "Advamced" Settimgs or somewhere discreet (in case this "tap" functionality might increase risk of app crashes))... i should have mentionwd I am **not** a dev so I 100% presume that apps (especially as clean, UI-friendly, intuitive, refined, and FUNCTIONAL as Workhorse vital apps are (I can not attest to Voiceliner yet having used it once, though, I have raved about it to self and have screenahots for all functions, export (options) and the *CLEAN* functionality no extraneous confuaing unnecessary crappy (fish) elements...) 

Potential suggestions/ideas:
"Tap" 
Include in Tutorial/instructions - i.e.:
- "...hold (or tap)..."
Include in Settimgs "help" menu OR, if liable t o cause crashes/beta feature/etc. ... DISCLAIMER that "tap" option with something like:
- [advanced option 'hint']: Tap (in lieu / instead of hold) also works; NOTE HOWEVER the likelihood of app crashes, transcription errors, transcription malfunction, aka *PROBLEMS* arise if recordings 
- - are *too* long
- - are longer than x:xx (i.e. 00:01:00 / 1 minute)
- - etc.

I dont know if this helps, and at the same time I hope ir does because 
1) I DIG Voiceliner and really hope to see continuous development
2) I believe in the value, potential, and meta-helpfulness of it and its capabikities (exisying and potential) and
3) ... (I could go on)...

For the sake of rhetorical feedback, not criticism, I foresee strong value in expanding the scope of the Voiceliner "vision" (*without* discreetly denotating/saying so... so as to include in the "aboit this app" app store sections the App Features that will be simple and little risk for the average user, and at the same time for a user (outside the "braindump... hold... record... transcribe... outline... export..." case scenario (for this purpose I will say an "Advanced User") of "advanced" / alterior / creative uses the "aboit this app" features, keywords, etc. can indicate the *POTENTIAL* uses of this app... and ***experiment***  (carefully perhaps might be wise, considering the app can not import audio, and transcribe imported audio, ... yet at least ;) ) mode can be tested ONLY IF/WHEN the user toggles the "advanced" settings which either:
A) State the option of "tapping" to record;
 -  perhaps with a disclaimer to help thebuser prevent potential problems, long less-than-optimal-for transcribing-recordings, crashes, etc.
B) toggles (an actual toggle in thw settings (code)) to allow 'long' recordings...
C)...? 

Feel free to jump in anyone and/or copy/paste this to a new issue as I
1) Firmly see value and benefit in Voiceliner and my respective commentary (here)(and elsewhwre IIRC)
2) Find others "chiming in" often clarifies my ideas (I can be long-winded)
3) I might be away for aome time (and thus unavailable to respond)
... err... 4)? ... 

Dude. Voiceliner.

---

P.p.s. If I wasn't clear, I realky appreciate the simplicity of Voiceliner... it is "smooth" "makes sense" and gers out of the way" for the user... *except* (in my case... the hold function (which might be an unusual/outlier use-case because as an artist I need to do as much as possible to make my brain think the recorder *zis *not* on... the more a recorder potentially exists in the room, the less natural and fluemt mynideas will flow, be, come out... Dunno if that makes sense...) ... Simple. user-Friendly...
With Advanced functionality under the hood (Logic Pro for example is relativy straight-dorward... and at the same time, if | when you read the manual and dig in... crazy craay adcanced neat advanced ... settimgs, experiments, functionalities, etc. Are available to be used, applied, etc. Like having a "sleeper" workhorse minivan that, if one reads the manual, can out-perform teucks, soundsyatems, military tanks, spaceships, ... perhaps that is a metaphor... 
Elon Musk might think otherwise ;) )

Great work. Grwat. Work. 
P.p.s. (p.p.p.s.?) The UI or UX struck me as iOS meets Android... that may have been a first for me... (That is REALLY cool, and if it took a lot of work, I am acknowledging that work, time, energy, effort, action, and result(s). Voiceliner seems to be firm in foundation. I hope my feedback is helpful, valuabke, critical, and tactdul... Your ego I hope not to affect  in a "not good" way, and I hope to express honest candid feedback that aims to be ripe with candor, emotion, foresight, vision, respectful and humble constructive crirtcism, ... my fratitudes and as always I encourage any and all feedback on my feesback (candor is apreciated, please just try not to make mean statements... aka "x/this is unnecessary,"  "i disagree with ___," ... vs ... well, this isn't Reddit I have yet to experience anything non-productive on Github. Wow. I just realized that. How cool this commumity is.)
